### ISSUE TITLE
[enhancement] When editing a list, auto start a line with list symbol

### ISSUE THREAD

**Issue by dimpflmoser** [scharel/harbour-nextcloudnotes#11]
If you edit a list, either bullet points, numbered list, or tick list and if you enter a line break I'd love to see automatic symbols of that list element in the next line. Especially for ticks (- [ ] mytext) is a pain to type with Sailfish keyboard.

**Comment by scharel** [comment]
I thought exactly the same while testing. Definitely on the TODO list.

**Comment by scharel** [comment]
This is implemented, you can download the latest version here: https://cloud.scharel.name/s/harbour-nextcloudnotes
