### ISSUE TITLE
Make Tick boxes case INsensitive

### ISSUE THREAD

**Issue by dimpflmoser** [scharel/harbour-nextcloudnotes#12]
As Joplin uses capital X for ticked boxes i'd love to see `- [x] mylabel` and `- [X] mylabel` will create ` ☑ mylabel`

**Comment by scharel** [comment]
Ok, this is easy, but I will keep the small x for the app because this is how the Showdown syntax is defined.

**Comment by scharel** [comment]
This is implemented, you can download the latest version here: https://cloud.scharel.name/s/harbour-nextcloudnotes
