### ISSUE TITLE
[bug] opening search result fails

### ISSUE THREAD

**Issue by dimpflmoser** [scharel/harbour-nextcloudnotes#14]
When clicking on a search result it opens the newest note and not the selected search result

BTW you're faster adding new features / closing issues than me creating new issues. ;-)

**Comment by scharel** [comment]
Ooops :blush: 
Also search looses focus while typing.
I must have busted it while changing something else.

**Comment by dimpflmoser** [comment]
Actually my search field allways shows 'Giesing' as prededined text, not sure where it comes from, could've been my first search that id doesn't even forget after restart. It's also not the clipboard. No clue where it has it from

**Comment by scharel** [comment]
I suspect 'Giesing' is how you named the nextcloud account?
I used the `placeholderText` of the `SearchField` as the title.

**Comment by dimpflmoser** [comment]
Ah, you're right! So it's not a bug, it's a feature.
