### ISSUE TITLE
[feature request] Add indent option for lists

### ISSUE THREAD

**Issue by dimpflmoser** [scharel/harbour-nextcloudnotes#15]
such as 

```
- first
- second
 - first indent
 - second indent
  - one more level
```
Of course I'd love to see that on tick boxes / todos as well.
And of course I'd love to see that if you press enter on an indented line the new line is auto-indented

I know I'm greedy. ;-)

**Comment by scharel** [comment]
Indent is already possible, you need to put four blanks in front ;)
But I need to improve the autoident, also for other items such as blockquotes, etc.

**Comment by dimpflmoser** [comment]
Ooops, four blanks is a lot, have seen one or in rare cases two blanks in other markdown.
Nevertheless, great to know. Your app is already much more powferful than the Notes web app that runs in Nextcloud

**Comment by scharel** [comment]
4 spaces is how markdown is defined and how [Showdown](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax) interprets it. So I will most probably keep it.

Maybe I can add a setting, but this has not so much priority at the moment.

**Comment by dimpflmoser** [comment]
alright, let's close it for the moment

**Comment by dimpflmoser** [comment]
Indents break the tick box of to level entries. I that on purpose?
```
- [ ] my top entry
    - [ ] first sub entry
```

**Comment by scharel** [comment]
This is indeed a bug ;)
