### ISSUE TITLE
Indents break the tick box

### ISSUE THREAD

**Issue by scharel** [scharel/harbour-nextcloudnotes#17]
```
- [ ] my top entry
    - [ ] first sub entry
```

_Originally posted by @dimpflmoser in https://github.com/scharel/harbour-nextcloudnotes/issues/15#issuecomment-444477673_

**Comment by dimpflmoser** [comment]
Maybe this is related:

an indented tick box cannot be ticked in view mode, also the `[x]` in edit mode gets replaced by `[ ]`

**Comment by scharel** [comment]
Try out v0.1-7.

**Comment by scharel** [comment]
> Actually, don't you think your app would be ready for public beta test?

Probably soon.
I want to fix the account creation first because this is the first step new users will perform,

**Comment by scharel** [comment]
I added the app to [OpenRepos](https://openrepos.net/content/scharel/nextcloud-notes).
