### ISSUE TITLE
[Feature Request] add Menu entry for Markdown Syntax

### ISSUE THREAD

**Issue by dimpflmoser** [scharel/harbour-nextcloudnotes#18]
I'm impressed that so much of the syntax is already implemented, please let the user know

**Comment by scharel** [comment]
Yes, currently you can open the wiki page of showdown from the edit page.
But I already thaught about adding something else.
Maye even an 'insert list/link/image/table...' dialog.

**Comment by scharel** [comment]
A page with most of the supported syntax can be opened from the pulley menu of the edit page.
