### ISSUE TITLE
[bug] notes without category are shown with a random category in list view

### ISSUE THREAD

**Issue by dimpflmoser** [scharel/harbour-nextcloudnotes#21]
I created a new note (actually copied markdownsyntax.ext into a new note) and it is tagged with an existing category, however if you open that note the category field is empty.
Actually all notes have are shown with a (random?) category in the list view, even if they do not have a category

**Comment by dimpflmoser** [comment]
I think I'm catching up with new issues. :-)

**Comment by dimpflmoser** [comment]
Not sure on rhe Notes version, I'm still on Nextcloud 13 and haven't updated either for a while.

Actually now I can't reproduce it either. Android Notes also doesn't show that.

I'd suggest to close this issue until it happens again.

**Comment by scharel** [comment]
Ok, I'm closing it then.
