### ISSUE TITLE
An app icon is needed

### ISSUE THREAD

**Issue by scharel** [scharel/harbour-nextcloudnotes#22]
An app icon according to this guide: https://sailfishos.org/design/icons/

**Comment by scharel** [comment]
> Maybe i can put together some drafts during christmas holidays.
> Got any desired motive?

That would be awesome! I'm really not good at graphics.
I'd like something similar than the icon on the server side or from the Android app to have some recognition factor.
But that is just my opinion.

**Comment by scharel** [comment]
@dotvhs Thank you for your contribution!
I do prefer the left icon.

How about adding some lines and/or a pencil to make it clearer that it is a notes app?

**Comment by oodport** [comment]
Whoops! Feel free to use this, but it looks like I am too late.
![harbour-nextcloudnotes](https://user-images.githubusercontent.com/48968713/106969132-42a64100-6718-11eb-81b7-96d4e8598a2a.png)

**Comment by oodport** [comment]
Thanks for this app! I think it is the only Nextcloud/Owncloud Notes app that still works on the Xperia 10 Plus.

I started this before noticed this issue, but here they are anyway.
![harbour-nextcloudnotes](https://user-images.githubusercontent.com/48968713/107092269-477afb80-67d1-11eb-8f94-5f91c5b673e2.png)
![harbour-nextcloudnotes-2](https://user-images.githubusercontent.com/48968713/107092272-477afb80-67d1-11eb-8012-47a525c0d5f2.png)

**Comment by scharel** [comment]
Thank you for you submissions!
Meanwhile I also created an icon myself (in this [branch](https://github.com/scharel/harbour-nextcloudnotes/blob/filebackend/icons/172x172/harbour-nextcloudnotes.png).

I have very limited time therefore development goes very slow :(
