### ISSUE TITLE
Edit involuntary renames file

### ISSUE THREAD

**Issue by fllp** [scharel/harbour-nextcloudnotes#35]
When creating a file outside of Harbour Notes via the desktop client, the file get renamed upon the first edit. The file's name will be the first line of the note's text.

When using special syntax for use in 3rd party editors such as tick boxes, this can lead to problematic filenames, containing characters such as `[ ]` or `%` (pandoc syntax). 

Also, the file names of notes contain spaces which can be called undesirable on a UNIX system :wink:   But this might be worth a dedicated issue.

**Comment by scharel** [comment]
This is the behavior of the server app.
Please have a look at the [Nextcloud Notes documentation](https://github.com/nextcloud/notes/wiki/Notes-0.2#update-a-note).
There's already a similar [issue](https://github.com/nextcloud/notes/issues/190) opened in the server repo.

So at the moment there's nothing I can do.
Probably one day one can think about moving away from the server-side Notes API and use WebDav and simple text-files instead.

**Comment by fllp** [comment]
Ah, I see. Thanks for clarifying. I'll close this then.
