### ISSUE TITLE
Possibility to save .md files

### ISSUE THREAD

**Issue by cy8aer** [scharel/harbour-nextcloudnotes#36]
It would be nice to have an option to save .md files instead of .txt files. On the nextcloud/owncloud side are markdown editors existent which only work with .md files.

**Comment by scharel** [comment]
The files on the server side are handled by the server app. But there is an Option in the serverside Notes App to set .md as the default.

**Comment by cy8aer** [comment]
oups, did not know about the option. Works smooth. Closing issue and thank you.
