### ISSUE TITLE
Use APIv1.x

### ISSUE THREAD

**Issue by stefan-niedermann** [scharel/harbour-nextcloudnotes#61]
Hey there :wave: 

i noticed, you are still connecting with API `v0.2` which is deprecated and will be removed in a future release.

I recommend you to update to [API `v1.x`](https://github.com/nextcloud/notes/blob/master/docs/api/v1.md) which is nearly identical - the efforts to switch should be minimal.

**Comment by scharel** [comment]
Thanks a lot for the comment. I plan to use newer API versions in the upcoming releases.
Unfortunately development makes very slow progress as I have very little time to work on the project.

**Comment by rubdos** [comment]
@stefan-niedermann is there a summary of API changes, somewhere? If there is one, I could check which changes we might still bump into.

**Comment by stefan-niedermann** [comment]
Check out https://github.com/nextcloud/notes/blob/main/docs/api/README.md

There's no "diff" but the changes are quite few. Most remarkable is a separate `title` attribute.
