### ISSUE TITLE
aarch64

### ISSUE THREAD

**Issue by merisilta** [scharel/harbour-nextcloudnotes#63]
Could you provide a version for aarch64 that one can install on Xperia 10 II please.
Thanks in advance.

**Comment by scharel** [comment]
As I recently bought an Xperia10II too, this will happen soon ;)

**Comment by merisilta** [comment]
Oh, quick answer. Many thanks!

**Comment by scharel** [comment]
Done with version 0.2-8 (2d7d81e578611c6b48d83a0e28e3b251a774819d)
